feat: sprint14 hw. Каркас сервиса для шеринга  вещей
IliaStarikov/java-shareit pull request #2
Opened 2024-09-18 01:12 UTC by IliaStarikov

2024-09-18 18:32 UTC, ErkinKasymaliev requested changes
привет, работа очень хорошая!
оставил комменты

2024-09-18 18:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        return !emails.contains(email);
давайте одним условием `return emails.isEmpty() || !emails.contains(email)`

2024-09-18 18:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exception/EmailIsBusy.java
> +public class EmailIsBusy extends RuntimeException {
AlreadyOccupiedEmailException

2024-09-18 18:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exception/ExceptionController.java
> +public class ExceptionController {
это не контроллер, это хэндлер) 
поэтому ExceptionHandler

2024-09-18 18:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exception/ExceptionController.java
> +    public Map<String, String> handleNotFoundEntityException(RuntimeException exception) {
ммм, у вас каждый exception будет отдавать разные по структуре ответы, не очень хорошее решение.
Создайте класс ErrorResponse или ExceptionResponse
примерно так:
class ErrorResponse {
 String message;
 //могут быть и еще другие поля

2024-09-18 18:32 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return new ArrayList<>(items.values()
new ArrayList не нужен:
```
return items.values().stream()
                .filter(item -> item.getOwnerId() == userId)
                .toList());
```

В других местах тоже поправьте

2024-09-26 05:43 UTC, IliaStarikov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        return !emails.contains(email);
исправлено

2024-09-26 05:44 UTC, IliaStarikov commented on src/main/java/ru/practicum/shareit/exception/EmailIsBusy.java
> +public class EmailIsBusy extends RuntimeException {
исправлено

2024-09-26 05:45 UTC, IliaStarikov commented on src/main/java/ru/practicum/shareit/exception/ExceptionController.java
> +public class ExceptionController {
исправлено

2024-09-26 05:52 UTC, IliaStarikov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return new ArrayList<>(items.values()
исправлено

2024-09-26 06:23 UTC, IliaStarikov commented on src/main/java/ru/practicum/shareit/exception/ExceptionController.java
> +    public Map<String, String> handleNotFoundEntityException(RuntimeException exception) {
исправлено

2024-09-26 14:10 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-09-27 13:03 UTC, merged